#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
pub struct DataPackHeader {
    pub start_code1: u8,
    pub start_code2: u8,
    pub tracking_type: u8,
    pub sub_type: u8,
    pub multi_pack: u8,
    pub current_index: u8,
    pub version: u16,
    pub timestamp: u64,
}

#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
pub struct DataPackBody {
    pub timestamp: i64,
    pub blend_shapes: [f32; 72],
    pub video_input_valid: [f32; 10],
    pub laughing_prob: f32,
    pub emotion_prob: [f32; 10],
    pub reserved: [f32; 128],
}

#[derive(Debug, Clone, Copy)]
#[repr(usize)]
pub enum PicoBlendShape {
    EyeLookDownL = 0,
    NoseSneerL = 1,
    EyeLookInL = 2,
    BrowInnerUp = 3,
    BrowDownR = 4,
    MouthClose = 5,
    MouthLowerDownR = 6,
    JawOpen = 7,
    MouthUpperUpR = 8,
    MouthShrugUpper = 9,
    MouthFunnel = 10,
    EyeLookInR = 11,
    EyeLookDownR = 12,
    NoseSneerR = 13,
    MouthRollUpper = 14,
    JawRight = 15,
    BrowDownL = 16,
    MouthShrugLower = 17,
    MouthRollLower = 18,
    MouthSmileL = 19,
    MouthPressL = 20,
    MouthSmileR = 21,
    MouthPressR = 22,
    MouthDimpleR = 23,
    MouthLeft = 24,
    JawForward = 25,
    EyeSquintL = 26,
    MouthFrownL = 27,
    EyeBlinkL = 28,
    CheekSquintL = 29,
    BrowOuterUpL = 30,
    EyeLookUpL = 31,
    JawLeft = 32,
    MouthStretchL = 33,
    MouthPucker = 34,
    EyeLookUpR = 35,
    BrowOuterUpR = 36,
    CheekSquintR = 37,
    EyeBlinkR = 38,
    MouthUpperUpL = 39,
    MouthFrownR = 40,
    EyeSquintR = 41,
    MouthStretchR = 42,
    CheekPuff = 43,
    EyeLookOutL = 44,
    EyeLookOutR = 45,
    EyeWideR = 46,
    EyeWideL = 47,
    MouthRight = 48,
    MouthDimpleL = 49,
    MouthLowerDownL = 50,
    TongueOut = 51,
    PP = 52,
    CH = 53,
    o = 54,
    O = 55,
    I = 56,
    u = 57,
    RR = 58,
    XX = 59,
    aa = 60,
    i = 61,
    FF = 62,
    U = 63,
    TH = 64,
    kk = 65,
    SS = 66,
    e = 67,
    DD = 68,
    E = 69,
    nn = 70,
    sil = 71,
}
