[package]
name = "vrft-vd-module"
version.workspace = true
edition.workspace = true

[lib]
name = "vd_module"
crate-type = ["cdylib"]

[dependencies]
vrft-api = { workspace = true }
memmap2 = "0.9"
glam = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_System_Memory",
]
