[package]
name = "vrft-common"
version.workspace = true
edition.workspace = true

[lib]
name = "vrft_common"

[dependencies]
glam = { workspace = true }
anyhow = { workspace = true }
vrft-api = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }

[features]
xtralog = []
